"""Style.css 확장 스크립트"""
new_css = (
"/* ============================================================\n"
"   NEW COMPONENTS (v2.0)\n"
"   ============================================================ */\n"
"\n"
"/* Layout Selection Cards */\n"
".layout-cards { display:flex; gap:12px; flex-wrap:wrap; margin-top:6px; }\n"
".layout-card {\n"
"  display:flex; flex-direction:column; align-items:center; gap:8px;\n"
"  padding:12px 16px; background:var(--glass-bg);\n"
"  border:2px solid var(--glass-border); border-radius:var(--radius-md);\n"
"  cursor:pointer; transition:all var(--transition-fast);\n"
"  color:var(--text-secondary); font-size:12px; text-align:center; min-width:80px;\n"
"}\n"
".layout-card:hover { border-color:var(--neon-blue); background:var(--glass-bg-hover); color:var(--text-primary); }\n"
".layout-card.active { border-color:var(--neon-blue); background:rgba(0,212,255,0.12); color:var(--neon-blue); box-shadow:0 0 12px rgba(0,212,255,0.25); }\n"
".layout-card span { line-height:1.4; }\n"
".layout-card small { font-size:10px; opacity:0.75; }\n"
"\n"
".layout-icon { display:grid; gap:3px; border:1.5px solid currentColor; border-radius:4px; padding:3px; }\n"
".layout-icon div { background:currentColor; border-radius:2px; opacity:0.7; }\n"
".layout-icon-strip4 { grid-template-columns:1fr; width:28px; }\n"
".layout-icon-strip4 div { height:7px; }\n"
".layout-icon-strip3 { grid-template-columns:1fr; width:28px; }\n"
".layout-icon-strip3 div { height:8px; }\n"
".layout-icon-grid22 { grid-template-columns:1fr 1fr; width:28px; }\n"
".layout-icon-grid22 div { height:10px; }\n"
"\n"
"/* Timer Buttons */\n"
".timer-options { padding:10px 14px; display:flex; flex-direction:column; gap:8px; }\n"
".timer-options label { font-size:12px; color:var(--text-secondary); font-weight:600; letter-spacing:0.5px; }\n"
".timer-btns { display:flex; gap:8px; }\n"
".timer-btn {\n"
"  flex:1; padding:8px 4px; background:var(--glass-bg);\n"
"  border:1.5px solid var(--glass-border); border-radius:var(--radius-sm);\n"
"  color:var(--text-secondary); font-size:13px; font-weight:700;\n"
"  transition:all var(--transition-fast); cursor:pointer; font-family:var(--font-primary);\n"
"}\n"
".timer-btn:hover { border-color:var(--neon-blue); color:var(--neon-blue); }\n"
".timer-btn.active { border-color:var(--neon-blue); background:rgba(0,212,255,0.18); color:var(--neon-blue); box-shadow:0 0 8px rgba(0,212,255,0.3); }\n"
".timer-btn:disabled { opacity:0.4; cursor:not-allowed; }\n"
"\n"
"/* Camera controls row */\n"
".camera-controls-row { display:flex; gap:8px; align-items:stretch; }\n"
".camera-controls-row .camera-select-container { flex:1; min-width:0; }\n"
".btn-icon {\n"
"  display:flex; align-items:center; justify-content:center;\n"
"  width:44px; min-width:44px; font-size:20px;\n"
"  border-radius:var(--radius-md); cursor:pointer; transition:all var(--transition-fast);\n"
"  background:var(--glass-bg); border:1px solid var(--glass-border);\n"
"}\n"
".btn-icon:hover { background:var(--glass-bg-hover); border-color:var(--neon-blue); transform:rotate(180deg); }\n"
"\n"
"/* Start Shooting Button */\n"
".btn-start-shooting { font-size:15px; padding:14px; letter-spacing:0.5px; animation:pulse-glow 2s ease-in-out infinite; }\n"
"@keyframes pulse-glow {\n"
"  0%,100% { box-shadow:0 0 12px rgba(0,212,255,0.3); }\n"
"  50% { box-shadow:0 0 24px rgba(0,212,255,0.6), 0 0 40px rgba(180,77,255,0.3); }\n"
"}\n"
"\n"
"/* Shoot Now Button */\n"
".btn-shoot-now {\n"
"  font-size:13px; padding:10px;\n"
"  border:2px solid var(--neon-pink); color:var(--neon-pink);\n"
"  background:rgba(255,107,202,0.12); animation:pulse-pink 1s ease-in-out infinite;\n"
"}\n"
".btn-shoot-now:hover { background:rgba(255,107,202,0.25); box-shadow:0 0 20px rgba(255,107,202,0.4); }\n"
"@keyframes pulse-pink {\n"
"  0%,100% { box-shadow:0 0 8px rgba(255,107,202,0.3); }\n"
"  50% { box-shadow:0 0 18px rgba(255,107,202,0.6); }\n"
"}\n"
"\n"
"/* Retake Tooltip */\n"
".retake-tooltip {\n"
"  position:absolute; bottom:20px; left:50%; transform:translateX(-50%);\n"
"  background:rgba(0,212,255,0.95); color:#08081a;\n"
"  padding:14px 18px; border-radius:var(--radius-md); font-size:13px; font-weight:600;\n"
"  text-align:center; box-shadow:0 4px 20px rgba(0,212,255,0.4);\n"
"  z-index:100; max-width:90%; line-height:1.5; animation:tooltip-in 0.3s ease-out;\n"
"}\n"
".tooltip-close { position:absolute; top:4px; right:6px; background:none; border:none; color:#08081a; font-size:14px; cursor:pointer; padding:2px 4px; opacity:0.7; }\n"
".tooltip-close:hover { opacity:1; }\n"
"@keyframes tooltip-in {\n"
"  from { opacity:0; transform:translateX(-50%) translateY(10px); }\n"
"  to   { opacity:1; transform:translateX(-50%) translateY(0); }\n"
"}\n"
"\n"
"/* Shot indicator */\n"
".shot-indicator-wrap { display:flex; align-items:center; justify-content:center; font-size:22px; font-weight:800; padding:10px; }\n"
".shot-current { color:var(--neon-blue); }\n"
".shot-total   { color:var(--text-secondary); font-size:16px; }\n"
"\n"
"/* RGB Color Picker swatch */\n"
".color-swatch-picker { position:relative; cursor:pointer; display:flex; align-items:center; justify-content:center; font-size:16px; overflow:hidden; }\n"
".color-swatch-picker input[type='color'] { position:absolute; inset:0; opacity:0; cursor:pointer; width:100%; height:100%; border:none; padding:0; }\n"
"\n"
"/* Style options grid */\n"
".style-options { display:flex; flex-wrap:wrap; gap:8px; padding:4px 0; }\n"
".style-option-item {\n"
"  display:flex; flex-direction:column; align-items:center; gap:4px; padding:6px;\n"
"  border-radius:var(--radius-sm); border:2px solid var(--glass-border);\n"
"  cursor:pointer; transition:all var(--transition-fast);\n"
"  background:var(--glass-bg); min-width:72px; text-align:center;\n"
"}\n"
".style-option-item canvas { width:60px; height:60px; border-radius:4px; }\n"
".style-option-item img { width:60px; height:60px; border-radius:4px; object-fit:cover; }\n"
".style-option-item span { font-size:10px; color:var(--text-secondary); line-height:1.3; }\n"
".style-option-item:hover { border-color:var(--neon-blue); background:var(--glass-bg-hover); }\n"
".style-option-item.active { border-color:var(--neon-blue); background:rgba(0,212,255,0.12); box-shadow:0 0 10px rgba(0,212,255,0.2); }\n"
".style-option-item.active span { color:var(--neon-blue); }\n"
"\n"
".custom-template-del { position:absolute; top:2px; right:2px; background:rgba(255,60,60,0.85); color:#fff; font-size:10px; border-radius:50%; width:18px; height:18px; display:flex; align-items:center; justify-content:center; cursor:pointer; opacity:0; transition:opacity 0.2s; }\n"
".custom-template-option { position:relative; }\n"
".custom-template-option:hover .custom-template-del { opacity:1; }\n"
".custom-template-area { display:flex; flex-direction:column; gap:8px; }\n"
".custom-templates-list { display:flex; flex-wrap:wrap; gap:8px; }\n"
".upload-label { display:inline-flex; align-items:center; justify-content:center; cursor:pointer; text-align:center; white-space:nowrap; }\n"
".btn-sm { padding:8px 16px !important; font-size:12px !important; min-height:36px !important; }\n"
".section-divider { border:none; border-top:1px solid var(--glass-border); margin:4px 0; }\n"
"\n"
"/* ============================================================\n"
"   RESPONSIVE BREAKPOINTS\n"
"   ============================================================ */\n"
"\n"
"/* MOBILE (< 600px) */\n"
"@media (max-width: 599px) {\n"
"  html, body { overflow:auto; }\n"
"  #app { height:auto; min-height:100dvh; position:relative; }\n"
"  .screen { position:relative; opacity:1; transform:none; display:none; pointer-events:none; }\n"
"  .screen.active { display:flex; pointer-events:auto; }\n"
"  #screen-start h1 { font-size:30px; }\n"
"  #screen-start .subtitle { font-size:11px; letter-spacing:4px; }\n"
"  .start-icon { font-size:52px; }\n"
"  .start-content { padding:20px 16px; gap:14px; }\n"
"  .btn-primary { padding:12px 24px; font-size:13px; min-height:48px; }\n"
"  .frame-select-body { flex-direction:column; gap:14px; padding:14px; }\n"
"  .frame-preview-container { max-height:220px; display:flex; align-items:center; justify-content:center; }\n"
"  #frame-preview { max-height:220px; max-width:100%; }\n"
"  .layout-card { min-width:68px; padding:9px 11px; font-size:11px; }\n"
"  .shoot-layout { flex-direction:column; height:auto; }\n"
"  .shoot-sidebar { width:100%; flex-direction:row; flex-wrap:wrap; padding:8px; gap:8px; overflow-x:auto; overflow-y:visible; max-height:none; border-top:1px solid var(--glass-border); border-left:none; }\n"
"  .shoot-sidebar > * { flex:1 1 auto; min-width:70px; }\n"
"  .shoot-preview-frame-container { display:none; }\n"
"  .timer-btn { padding:6px 4px; font-size:12px; }\n"
"  .shot-indicator-wrap { font-size:15px; padding:8px; }\n"
"  .btn-start-shooting, .btn-shoot-now { font-size:12px; padding:8px; min-height:38px; }\n"
"  .edit-body { flex-direction:column; overflow-y:auto; height:auto; }\n"
"  .edit-preview-container { width:100%; height:48vw; min-height:180px; overflow:hidden; flex:0 0 auto; }\n"
"  #edit-canvas { max-height:48vw; width:auto; max-width:100%; margin:0 auto; }\n"
"  .edit-controls { width:100%; max-height:none; overflow:visible; padding:10px; gap:10px; border-top:1px solid var(--glass-border); border-left:none; flex:1 1 auto; }\n"
"  #sticker-list { max-height:130px; }\n"
"  .style-option-item canvas, .style-option-item img { width:44px; height:44px; }\n"
"  .style-option-item { min-width:56px; }\n"
"  .result-body { flex-direction:column; padding:14px; gap:16px; }\n"
"  .result-preview { max-height:55vw; width:100%; overflow:hidden; }\n"
"  #result-image { max-height:55vw; margin:0 auto; }\n"
"  .action-buttons { flex-direction:row; flex-wrap:wrap; gap:8px; justify-content:center; }\n"
"  .action-buttons .btn-primary, .action-buttons .btn-secondary { padding:10px 14px; font-size:12px; min-height:42px; }\n"
"  .screen-header { padding:10px 14px 0; }\n"
"  .screen-header h2 { font-size:15px; }\n"
"}\n"
"\n"
"/* SMALL TABLET (600px - 767px) */\n"
"@media (min-width: 600px) and (max-width: 767px) {\n"
"  html, body { overflow:auto; }\n"
"  #app { height:auto; min-height:100dvh; position:relative; }\n"
"  .screen { position:relative; opacity:1; transform:none; display:none; pointer-events:none; }\n"
"  .screen.active { display:flex; pointer-events:auto; }\n"
"  #screen-start h1 { font-size:42px; }\n"
"  .start-icon { font-size:70px; }\n"
"  .frame-select-body { flex-direction:row; gap:20px; padding:20px; }\n"
"  .frame-preview-container { max-width:180px; max-height:280px; }\n"
"  .shoot-sidebar { width:180px; padding:12px 8px; gap:8px; }\n"
"  .edit-body { flex-direction:row; }\n"
"  .edit-preview-container { flex:1; min-height:300px; }\n"
"  .edit-controls { width:250px; min-width:200px; border-left:1px solid var(--glass-border); padding:14px; }\n"
"  #sticker-list { max-height:180px; }\n"
"  .result-body { flex-direction:row; gap:24px; padding:20px; }\n"
"  .result-preview { max-height:70vh; }\n"
"  #result-image { max-height:70vh; }\n"
"  .action-buttons { flex-direction:column; }\n"
"  .screen-header { padding:14px 18px 0; }\n"
"  .screen-header h2 { font-size:18px; }\n"
"}\n"
"\n"
"/* TABLET (768px - 1023px) */\n"
"@media (min-width: 768px) and (max-width: 1023px) {\n"
"  #screen-start h1 { font-size:56px; }\n"
"  .start-icon { font-size:84px; }\n"
"  .frame-select-body { gap:32px; padding:24px 32px; }\n"
"  #frame-preview { max-height:62vh; }\n"
"  .shoot-sidebar { width:220px; padding:14px 10px; }\n"
"  .edit-body { flex-direction:row; }\n"
"  .edit-preview-container { flex:1; max-height:none; background:#000; }\n"
"  .edit-controls { width:280px; min-width:240px; max-width:48vw; padding:16px; border-left:1px solid var(--glass-border); }\n"
"  #sticker-list { max-height:220px; }\n"
"  .result-body { flex-direction:row; padding:28px 40px; gap:36px; }\n"
"  .result-preview { max-height:80vh; }\n"
"  #result-image { max-height:80vh; }\n"
"  .action-buttons { flex-direction:column; }\n"
"  .screen-header { padding:20px 28px 0; }\n"
"  .screen-header h2 { font-size:22px; }\n"
"}\n"
"\n"
"/* PC (>= 1024px) */\n"
"@media (min-width: 1024px) {\n"
"  #screen-start h1 { font-size:72px; }\n"
"  .start-icon { font-size:100px; }\n"
"  .btn-primary { padding:18px 52px; font-size:17px; min-height:60px; }\n"
"  .frame-select-body { gap:48px; padding:32px 48px; }\n"
"  #frame-preview { max-height:70vh; }\n"
"  .shoot-sidebar { width:260px; padding:16px 12px; gap:12px; }\n"
"  .edit-body { flex-direction:row; }\n"
"  .edit-preview-container { flex:1 1 auto; max-height:none; background:#000; align-self:stretch; }\n"
"  #edit-canvas { max-height:100%; max-width:100%; border-radius:0; }\n"
"  .edit-controls { flex:0 0 auto; width:var(--sidebar-width); min-width:260px; max-width:52vw; border-left:1px solid var(--glass-border); padding:20px; gap:14px; }\n"
"  #sticker-list { max-height:280px; }\n"
"  .sticker-item { width:54px; height:54px; font-size:26px; }\n"
"  .result-body { flex-direction:row; align-items:center; padding:32px 48px; gap:48px; flex-wrap:nowrap; }\n"
"  .result-preview { max-height:85vh; }\n"
"  #result-image { max-height:85vh; }\n"
"  .result-actions-panel { max-width:480px; }\n"
"  .action-buttons { flex-direction:column; }\n"
"  .screen-header { padding:24px 32px 0; }\n"
"  .screen-header h2 { font-size:26px; }\n"
"}\n"
"\n"
"/* EXTRA LARGE (>= 1440px) */\n"
"@media (min-width: 1440px) {\n"
"  :root { --sidebar-width:420px; }\n"
"  #screen-start h1 { font-size:88px; }\n"
"  .shoot-sidebar { width:320px; }\n"
"}\n"
"\n"
"@supports (padding: env(safe-area-inset-top)) {\n"
"  @media (min-width: 600px) {\n"
"    .screen { padding-top:env(safe-area-inset-top); padding-bottom:env(safe-area-inset-bottom); padding-left:env(safe-area-inset-left); padding-right:env(safe-area-inset-right); }\n"
"    #screen-shoot { padding:0; }\n"
"    .shoot-sidebar { padding-top:calc(16px + env(safe-area-inset-top)); padding-bottom:calc(16px + env(safe-area-inset-bottom)); }\n"
"  }\n"
"}\n"
"\n"
"::-webkit-scrollbar { width:4px; height:4px; }\n"
"::-webkit-scrollbar-track { background:transparent; }\n"
"::-webkit-scrollbar-thumb { background:var(--glass-border); border-radius:2px; }\n"
"::-webkit-scrollbar-thumb:hover { background:var(--text-dim); }\n"
"button:focus-visible, input:focus-visible { outline:2px solid var(--neon-blue); outline-offset:2px; }\n"
"@media (prefers-reduced-motion: reduce) { *,*::before,*::after { animation-duration:0.01ms !important; animation-iteration-count:1 !important; transition-duration:0.01ms !important; } }\n"
"@media print { body { display:none; } }\n"
)

with open('style.css', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Keep up to splash text (line 826 = index 825), remove old responsive section
kept = lines[:827]
kept.append(new_css)

with open('style.css', 'w', encoding='utf-8') as f:
    f.writelines(kept)

print('style.css updated successfully.')
